GET http://localhost:8080/test
Authorization: Basic ajinkya:aj1234

###

GET http://localhost:8080/videos
Authorization: Basic ajinkya:aj1234

###

POST http://localhost:8080/videos
Authorization: Basic ajinkya:aj1234

{
    "title": "title 1",
    "description": "desc 1",
    "url": "https://youtube.com/abcd",
    "author": {
        "firstname": "test",
        "lastname": "Abc",
        "age": 20,
        "email": "abc@gmail.com"
    }
}